version: '3'
services:
  nestjs:
    image: tuananh2911/nestjs
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '5000:5000' # expose-to-the-world : only-in-the-docker
    container_name: backend-app
    volumes:
      - .:/usr/src/app
    networks:
      - server

volumes:
  pgdata:
  pgadmin-data:
networks:
  server: